version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  flask-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: flask-api
    ports:
      - "5000:5000"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.wrk
    container_name: worker
    depends_on:
      - redis
