--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: ghg-redis-server 
  labels:
    username: aan1
    env: test
spec: 
  type: ClusterIP 
  selector: 
    app: ghg-api-data
  ports: 
  - name: ghg-api-data
    port: 6379
    targetPort: 6379 