--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: ghg-analysis-worker
  labels: 
    app: ghg-api-worker
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: ghg-api-worker 
  template: 
    metadata: 
      labels: 
        app: ghg-api-worker 
    spec: 
      containers: 
        - name: ghg-analysis-worker
          imagePullPolicy: Always 
          image: <...> 