--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: ghg-analysis-api
  labels:
    username: aan1
    env: test
spec: 
  type: ClusterIP 
  selector: 
    app: ghg-client-api
  ports: 
  - name: ghg-analysis-api
    port: 5000
    targetPort: 5000 